---

# Copyright 2022 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Primary entrypoint for all CDP installations (Public Cloud, Private Cloud)
#
# There are five "core" runlevels:
# - validate
# - initialize
# - infra
# - plat
# - run
# - teardown
#
# In this context, 'run' means 'runtime' or 'application'. The platform level
# is now both CDP Public Cloud SDX and Data Services, which is a change from
# from before where 'plat' referred to the DL and SDX and 'run' referred to the
# Data Services.
# 
# Individual Data Services (and Datahubs) should be tagged _within_ the 
# 'cloudera.exe.*' roles themselves:
# - de
# - df
# - dh
# - dw
# - ml
# - opdb

- name: Establish Cloudera Deploy runlevels
  hosts: localhost
  gather_facts: no
  run_once: True
  tags: always
  tasks:
    - ansible.builtin.import_role:
        name: runlevels

- name: Initialize Cloudera Deploy parameters
  hosts: localhost
  gather_facts: yes
  tags: always
  tasks:
    - ansible.builtin.import_role:  
        name: initialize_parameters # Should/could be more granular

- ansible.builtin.import_playbook: "{{ [definition_path | default('default'), 'post_teardown.yml'] | path_join }}"
  tags: ['never', 'plat', 'infra', 'teardown']
  when: hostvars.localhost.run_infrastructure or hostvars.localhost.run_platform or hostvars.localhost.run_teardown

- ansible.builtin.import_playbook: cloud_teardown.yml
  tags: ['never', 'infra', 'teardown']
  when: hostvars.localhost.run_infrastructure or hostvars.localhost.run_teardown

- ansible.builtin.import_playbook: cluster_teardown.yml
  tags: ['never', 'infra', 'teardown']
  when: hostvars.localhost.run_infrastructure or hostvars.localhost.run_teardown

- ansible.builtin.import_playbook: "{{ [definition_path | default('default'), 'pre_setup.yml'] | path_join }}"
  tags: ['run', 'plat', 'infra']
  when: hostvars.localhost.run_infrastructure or hostvars.localhost.run_platform or hostvars.localhost.run_runtime

- ansible.builtin.import_playbook: cloud_setup.yml
  tags: ['run', 'plat']
  when: hostvars.localhost.run_platform or hostvars.localhost.run_runtime

- ansible.builtin.import_playbook: cluster_setup.yml
  tags: ['run', 'plat']
  when: hostvars.localhost.run_platform or hostvars.localhost.run_runtime

- ansible.builtin.import_playbook: "{{ [definition_path | default('default'), 'post_setup.yml'] | path_join }}"
  tags: ['run']
  when: hostvars.localhost.run_runtime

- ansible.builtin.import_playbook: "{{ [definition_path | default('default'), 'pre_teardown.yml'] | path_join }}"
  tags: ['never', 'teardown']
  when: hostvars.localhost.run_teardown
