---

- name: Fetch necessary variables from Ansible Controller
  ansible.builtin.set_fact:
    globals: "{{ hostvars['localhost']['globals'] }}"
    init__download_mirror_artefact: "{{ hostvars['localhost']['init__download_mirror_artefact'] }}"

- name: Prepare Cloudera Subscription Credentials
  ansible.builtin.include_role:
    name: cloudera.cluster.deployment.credential
  when: globals.cloudera_license_file is defined
  vars:
    cloudera_manager_license_file: "{{ globals.cloudera_license_file }}"

- name: Populate the Download Mirror with new files
  ansible.builtin.include_role:
    name: cloudera_deploy
    tasks_from: populate_download_mirror
  when: globals.download_mirror_targets | length > 0
