---

- name: Refresh Listing of target cache contents
  when:
    - init__download_mirror_bucket_name is defined
    - "'teardown' not in ansible_run_tags"
  register: __infra_download_mirror_listing
  failed_when:
    - __download_mirror_lookup_initial.s3_keys is not defined
    - "'cannot be found' not in __download_mirror_lookup_initial.msg"
  amazon.aws.aws_s3:
    bucket: "{{ init__download_mirror_bucket_name }}"
    mode: list

- name: Prepare updated Download Mirror contents as URLs
  when: __infra_download_mirror_listing.s3_keys is defined
  loop: "{{ __infra_download_mirror_listing.s3_keys }}"
  loop_control:
    loop_var: __download_mirror_s3_urls_item
  ansible.builtin.set_fact:
    __download_mirror_url_listing: "{{ __download_mirror_url_listing | default([]) + [['https:/', init__download_mirror_bucket_name + '.s3.amazonaws.com', __download_mirror_s3_urls_item ] | join('/') ] }}"

- name: Persist Download Mirror to Definition path
  when:
    - __download_mirror_url_listing is defined
    - __download_mirror_url_listing | length > 0
  community.general.ini_file:
    path: "{{ init__download_mirror_artefact }}"
    section: "{{ globals.infra_type }}:{{ globals.region }}"
    option: "{{ init__download_mirror_bucket_name }}"
    value: "{{ __download_mirror_url_listing }}"