---

- name: Example pre-deploy set up playbook
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

# Inherits 'infra', 'plat', and 'run' from playbook import
# Applies 'validate' and 'initialize' via role import
# Data Service runtimes, like 'dw' and 'ml', can applied selectively
# within a role's tasks or via role import, as below
    
    - name: Start pre-deployment tasks
      debug:
        msg: This is the start.

    - name: Validate Infrastructure configuration
      ansible.builtin.import_role:
        name: cloudera.exe.infrastructure
        tasks_from: validate
      tags:
        - validate
        - de
        - df
        - dh
        - dw
        - ml
        - opdb

    - name: Initialize Infrastructure setup
      #when: sequence__setup_infra | bool
      ansible.builtin.import_role:
        name: cloudera.exe.infrastructure
        tasks_from: initialize_setup
      tags:
        - initialize
        - de
        - df
        - dh
        - dw
        - ml
        - opdb

    - name: Set up Infrastructure
      #when: sequence__setup_infra | bool
      ansible.builtin.include_role:
        name: cloudera.exe.infrastructure
        tasks_from: setup
      tags:
        - de
        - df
        - dh
        - dw
        - ml
        - opdb